version: "3.3"
services:
  subspace:
   image: subspacecommunity/subspace:amd64-v1.5.0
   container_name: subspace
   volumes:
    - /opt/docker/subspace:/data
    - /opt/docker/dnsmasq:/etc/dnsmasq.d
   restart: always
   environment:
    - SUBSPACE_HTTP_HOST=subspace.aparavi.com
    - SUBSPACE_LETSENCRYPT=true
    - SUBSPACE_HTTP_INSECURE=false
    - SUBSPACE_HTTP_ADDR=":80"
    - SUBSPACE_NAMESERVERS=10.64.0.4
    - SUBSPACE_LISTENPORT=51820
    - SUBSPACE_IPV4_POOL=10.99.97.0/24
    - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
    - SUBSPACE_IPV4_GW=10.99.97.1
    - SUBSPACE_IPV6_GW=fd00::10:97:1
    - SUBSPACE_IPV6_NAT_ENABLED=0
    - SUBSPACE_IPV4_NAT_ENABLED=false
    - SUBSPACE_DISABLE_DNS=0
    - SUBSPACE_PERSISTENT_KEEPALIVE=20
    - SUBSPACE_ALLOWED_IPS=10.64.0.0/19,10.99.97.1/32,146.75.0.0/16,151.101.0.0/16,3.93.122.172/32,3.228.51.180/32,34.204.106.166/32,34.237.69.2/32,54.160.40.164/32,54.162.34.73/32,2a04:4e42:79::561/128
   cap_add:
    - NET_ADMIN
   network_mode: "host"