---

- name: base
  hosts: all
  become: yes
  roles:
    - prometheus-node-exporter
    - logs-collection
  vars:
    - logstash_address: 'logstash.aparavi.com'
    - node_meta_env: 'prod'
    - node_meta_service: 'aparavi'
    - node_meta_component: 'appagent'
    - node_meta_subcomponent: 'app'
    - node_meta_service_instance: 'new_client_name'
