---

- name: base
  hosts: all
  become: yes
  roles:
    - prometheus-node-exporter
    - logs-collection
  vars:
    - grafana_url: 'https://dashboard.aparavi.com'
    - logstash_address: 'logstash.aparavi.com'
    - es_url: 'https://es.aparavi.com:9200'
    - kibana_url: 'https://kibana.aparavi.com'
    - victoriametrics_url: 'https://vm.aparavi.com'
