---

version: '3.5'
services:
  vmagent:
    container_name: 'vmagent'
    image: 'victoriametrics/vmagent'
    ports:
      - '8429:8429'
    volumes:
      - 'vmagentdata:/vmagentdata'
      - './vmagent/:/etc/vmagent/'
    command:
      - '--promscrape.config=/etc/vmagent/vmagent.yml'
      - '--remoteWrite.url=${VM_EXTERNAL_URL}'
      - '--remoteWrite.label=env=${ENVIRONMENT}'
      - '--remoteWrite.label=service_instance=${SERVICE_INSTANCE}'
    restart: 'unless-stopped'
volumes:
  vmagentdata: {}
