---

version: '3.5'
services:
  vmagent:
    container_name: 'vmagent'
    image: 'victoriametrics/vmagent'
    ports:
      - '8429:8429'
    volumes:
      - 'vmagentdata:/vmagentdata'
      - './vmagent/:/etc/vmagent/'
    command:
      - '--promscrape.config=/etc/vmagent/vmagent.yml'
      - '--remoteWrite.url=http://victoriametrics:8428/api/v1/write'
    restart: 'on-failure'
volumes:
  vmagentdata: {}
