---

- name: Wazuh agent | Add repository key
  apt_key:
    id: "{{ wazuh_repository_key_id }}"
    url: "{{ wazuh_repository_key_url }}"
    state: present
  tags:
    - wazuh_agent

- name: Wazuh agent | Add repository
  apt_repository:
    filename: wazuh_repo
    repo: "deb https://packages.wazuh.com/{{ wazuh_main_version }}.x/apt/ stable main"
    state: present
  tags:
    - wazuh_agent

- name: Wazuh agent | Install wazuh agent | latest
  apt:
    pkg: "wazuh-agent"
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_host }}"
    WAZUH_AGENT_NAME: "{{ node_meta_service_instance }}-{{ ansible_hostname }}"
  tags:
    - wazuh_agent
  when: wazuh_agent_full_version is not defined

- name: Wazuh agent | Install wazuh agent | not latest
  apt:
    pkg: "wazuh-agent={{ wazuh_agent_full_version }}"
    state: present
    allow_downgrade: yes
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_host }}"
    WAZUH_AGENT_NAME: "{{ node_meta_service_instance }}-{{ ansible_hostname }}"
  tags:
    - wazuh_agent
  when: wazuh_agent_full_version is defined

- name: Wazuh agent | Ensure Wazuh agent is started and enabled
  service:
    name: wazuh-agent
    state: started
    enabled: true
    daemon_reload: true
  when: wazuh_agent_service_state != 'stopped'
  tags:
    - wazuh_agent

- name: Wazuh agent | Ensure Wazuh agent is stopped and disabled (if wazuh_agent_service_state "started")
  service:
    name: wazuh-agent
    state: stopped
    enabled: false
    daemon_reload: true
  when: wazuh_agent_service_state == 'stopped'
  tags:
    - wazuh_agent
