---

- name: Wazuh agent | Add repository key
  apt_key:
    id: "{{ wazuh_repository_key_id }}"
    url: "{{ wazuh_repository_key_url }}"
    state: present

- name: Wazuh agent | Add repository
  apt_repository:
    filename: wazuh_repo
    repo: "deb https://packages.wazuh.com/{{ wazuh_main_version }}.x/apt/ stable main"
    state: present

- name: Wazuh agent | Install wazuh agent
  apt:
    pkg: "wazuh-agent={{ wazuh_agent_full_version }}"
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_host }}"
    # WAZUH_AGENT_NAME: "{{ client_name }}-{{ ansible_hostname }}"


- name: Wazuh agent | Ensure Wazuh agent is started and enabled
  service:
    name: wazuh-agent
    state: started
    enabled: true
    daemon_reload: true
  when: wazuh_agent_service_state != 'stopped'

- name: Wazuh agent | Ensure Wazuh agent is stopped and disabled (if wazuh_agent_service_state "started")
  service:
    name: wazuh-agent
    state: stopped
    enabled: false
    daemon_reload: true
  when: wazuh_agent_service_state == 'stopped'
