---

- name: MySQL | Install
  include_tasks:
    file: install.yml
    apply:
      tags:
        - mysql_server
  tags:
    - install
    - mysql_server

- name: MySQL | Configure
  include_tasks:
    file: config.yml
    apply:
      tags:
        - mysql_server
  tags:
    - configure
    - mysql_server

- name: MySQL | Users
  include_tasks: 
    file: users.yml
    apply:
      tags:
        - mysql_server
  tags:
    - configure
    - users
    - mysql_server

- name: MySQL | Databases
  include_tasks: 
    file: databases.yml
    apply:
      tags:
        - mysql_server
  tags:
    - configure
    - databases
    - mysql_server

- name: MySQL | Service
  include_tasks: 
    file: service.yml
    apply:
      tags:
        - mysql_server
  tags:
    - service
    - mysql_server
