---

- name: MySQL | Install
  import_tasks: install.yml
  tags:
    - install
    - mysql_server

- name: MySQL | Configure
  import_tasks: config.yml
  tags:
    - configure
    - mysql_server

- name: MySQL | Users
  import_tasks: users.yml
  tags:
    - configure
    - users
    - mysql_server

- name: MySQL | Databases
  import_tasks: databases.yml
  tags:
    - configure
    - databases
    - mysql_server

- name: MySQL | Service
  import_tasks: service.yml
  tags:
    - service
    - mysql_server
