---
- set_fact:
    mysql_root_password: "{{ mysql_root_password_gen }}"
    mysql_appuser_password: "{{ mysql_appuser_password_gen }}"

- debug:
    msg: "This password appears only once. You wll never see it again. Password {{ mysql_root_password }} and {{ mysql_appuser_password }}"

- debug:
    msg: "This password appears only once. You wll never see it again. Password {{ mysql_root_password }} and {{ mysql_appuser_password }}"

- name: MySQL | Set root password
  mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
    login_user: root
    login_host: localhost
  when: "installed_mysql.stdout != 'Status: install ok installed'"
###  notify: restart mysql

- name: MySQL | Ensure MySQL users are present
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{  item.priv | default(['*.*:USAGE']) | join('/') }}"
    append_privs: true
  with_items: "{{ mysql_users }}"
