---
- name: MySQL | Generate root password
  set_fact:
    mysql_root_password: "{{ mysql_root_password_gen }}"
    mysql_appuser_password: "{{ mysql_appuser_password_gen }}"

- name: MySQL | Retrieving MySQL password
  debug:
    msg: 
      - "Make sure to copy your database root password now."
      - "MySQL root password: {{ mysql_root_password }}"
      - "Make sure you copied the password without the closing quotes"

- name: MySQL | Set root password
  mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true
###  when: "installed_mysql.stdout != 'Status: install ok installed'"

- name: MySQL | Write mysql root password
  copy:
    content: "{{ mysql_root_password }}" 
    dest: "{{ install_tmp_dir }}/mysql_root_password.txt"

- name: MySQL | Create .my.cnf
  template:
    src: "client.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: MySQL | Ensure MySQL users are present
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{  item.priv | default(['*.*:USAGE']) | join('/') }}"
    append_privs: true
  with_items: "{{ mysql_users }}"
