---

mysql_root_password_gen: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits') }}"
mysql_appuser_password_gen: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits') }}"

mysql_deb_package: "mysql-apt-config_{{ mysql_version }}_all.deb"
mysql_deb_repo: "https://dev.mysql.com/get/{{ mysql_deb_package }}"

mysql_packages:
  - mysql-common
  - mysql-server

mysql_databases:
  - name: "{{ mysql_db_name }}"
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
  - name: "{{ mysql_platform_db_name }}"
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    
mysql_users:
  - name: "{{mysql_appuser_name}}"
    host: "%"
    password: "{{ mysql_appuser_password }}"
    priv:
      - '{{ mysql_db_name }}.*:ALL'
      - 'platform_%.*:ALL'
