---

- name: Debian 11 hardening
  hosts: 
    - "all"
  become: true
  gather_facts: true
  roles:
    - os_hardening
    - ssh_hardening
  vars:
    - ssh_client_password_login: true
    - ssh_server_password_login: true
    - sshd_authenticationmethods: "publickey password"
