---

- name: Debian 11 Aparavi
  hosts: 
    - "all"
  become: true
  gather_facts: true
  roles:
    - os_hardening
    - ssh_hardening
    - wazuh-agent
    - aparavi
    - wazuh-agent
    - clamav-agent
  vars:
    - ssh_client_password_login: true
    - ssh_server_password_login: true
    - sshd_authenticationmethods: "publickey password"
