---

- name: 'Set Facts | Fail on unsupported init systems'
  debug:
    msg: 'Using init.d scirpt, not a systemd OS'
  when: 'ansible_service_mgr != "systemd"'

- name: 'Set Facts | Check collectors'
  fail:
    msg: 'Collector cannot be both disabled and enabled'
  loop: '{{ node_exporter_disabled_collectors }}'
  when: 'item in node_exporter_enabled_collectors'


- name: 'Set Facts | Include main variables'
  include_vars:
    file: 'main.yml'
    name: 'node_exporter_common'

- name: 'Set Facts | Gather variables for each operating system'
  include_vars:
    dir: '{{ item }}'
    name: 'node_exporter_custom'
  with_first_found:
    - '{{ ansible_os_family | lower }}/{{ ansible_distribution_major_version }}'
    - '{{ ansible_os_family | lower }}'

- name: 'Set Facts | Set architecture variable if presents in var file'
  set_fact:
    node_exporter_arch: '{{ node_exporter_common.go_arch_map[ansible_architecture] }}'
  when: 'node_exporter_common.go_arch_map[ansible_architecture] is defined'

- name: 'Set Facts | Set architecture variable if does not present in var file'
  set_fact:
    node_exporter_arch: '{{ ansible_architecture }}'
  when: 'node_exporter_common.go_arch_map[ansible_architecture] is not defined'

- name: 'Set Facts | Set all required facts'
  set_fact:
    node_exporter_sha_url: '{{ node_exporter_common.base_url }}/sha256sums.txt'
    node_exporter_tar_url: '{{ node_exporter_common.base_url }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz'

