---

# Compliance
# cis: 1.1.1.7
# cis_csc: 5.1
# pci_dss: 2.2.5
# tsc: CC6.3
- name: Wazuh | 2506 | Ensure mounting of FAT filesystems is disabled | /etc/modprobe.d/
  file:
    path: /etc/modprobe.d
    state: directory

- name: Wazuh | 2506 | Ensure mounting of FAT filesystems is disabled | modprobe
  modprobe:
    name: vfat
    state: absent
  when: disable_vfat

- name: Wazuh | 2506 | Ensure mounting of FAT filesystems is disabled | /etc/modprobe.d/
  lineinfile:
    dest: /etc/modprobe.d/vfat.conf
    regexp: '^.*install vfat.*$'
    line: "install vfat /bin/true"
    create: true
  when: disable_vfat

# Compliance
# cis: 1.1.23
# cis_csc: 8.4,8.5
# nist_800_53: CM.1
# pci_dss: 2.2.5
# tsc: CC6.3
- name: Wazuh | 2524 | Disable USB Storage | /etc/modprobe.d/
  lineinfile:
    dest: /etc/modprobe.d/usb_storage.conf
    regexp: '^.*install usb-storage.*$'
    line: "install usb-storage /bin/true"
    create: true

- name: Wazuh | 2524 | Disable USB Storage | modprobe
  modprobe:
    name: usb-storage
    state: absent

# Compliance
# cis: 1.3.2
# cis_csc: 4.3
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh |  2526 | Ensure sudo commands use pty | /etc/sudoers.d/
  file:
    path: /etc/sudoers.d
    state: directory

- name: Wazuh | 2526 | Ensure sudo commands use pty
  lineinfile:
    dest: /etc/sudoers.d/pty
    regexp: '^.*Defaults use_pty.*'
    line: "Defaults use_pty"
    validate: "visudo -cf %s"
    create: yes

# Compliance
# cis: 1.3.3
# cis_csc: 6.3
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh | 2527 | Ensure sudo log file exists
  lineinfile:
    dest: /etc/sudoers.d/sudo_logs
    regexp: '^.*Defaults logfile.*'
    line: 'Defaults logfile="/var/log/sudo.log"'
    validate: "visudo -cf %s"
    create: yes
    state: present


# Compliance
# cis: 1.5.1
# cis_csc: 5.1
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh | 2530 | Ensure permissions on bootloader config are configured
  file:
    path: "/boot/grub/grub.cfg"
    mode: 0400
    owner: root
    group: root

######## TO DO ########
### - name: Wazuh | 2531 | Ensure bootloader password is set

# Compliance
# cis: 1.5.3
# cis_csc: 5.1
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh | 2532 | Ensure authentication required for single user mode
  shell: grep '^root:[*\!\:]' /etc/shadow
  register: root_password_check
  changed_when: false
  failed_when: false
  check_mode: no

- name: Wazuh | 2532 | Ensure authentication required for single user mode | generate password
  set_fact:
    root_password: "{{ root_password_gen }}"
  when: 
    - root_password_check.rc == 0

- name:  Wazuh | 2532 | Ensure authentication required for single user mode | set root password
  user:
    name: "root"
    state: present
    password: "{{ root_password | password_hash('sha512') }}"
  when: 
    - root_password_check.rc == 0

######## TO DO ########
### - name: Wazuh | 2533 | Ensure XD/NX support is enabled

# Compliance
# cis: 1.6.4
# cis_csc: 13
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh | 2536 | Ensure core dumps are restricted | limits
  lineinfile:
    dest: /etc/security/limits.d/core.conf
    line: "*               hard    core            0"
    regexp: '^\s*(#)?\*\s+hard\s+core\s+\d+'
    create: true

- name: Wazuh | 2536 | Ensure core dumps are restricted | sysctl
  sysctl:
    name: fs.suid_dumpable
    value: "0"
    sysctl_file: /etc/sysctl.d/fs-suid_dumpable.conf
    state: present
    reload: true
    sysctl_set: yes

- name: Wazuh | 2536 | Ensure core dumps are restricted | apt
  apt:
    name: systemd-coredump
    state: present

- name: Wazuh | 2536 | Ensure core dumps are restricted | daemon_reload
  systemd:
    daemon_reload: yes

# Compliance
# cis: 1.7.1.1
# cis_csc: 14.6
# nist_800_53: CM.1
# pci_dss: 2.2.4
# tsc: CC5.2
- name: Wazuh | 2537 | Ensure AppArmor is installed
  apt:
    pkg:
    - apparmor
    - apparmor-utils

# Compliance
# cis: 1.8.1.1
# cis_csc: 5.1
# pci_dss: 7.1
# tsc: CC6.4
- name: Wazuh | 2541 | Ensure message of the day is configured properly
  template:
    src: motd.j2
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root

# Compliance
# cis: 1.8.1.2
# cis_csc: 5.1
# pci_dss: 7.1
# tsc: CC6.4
- name: Wazuh | 2542 | Ensure local login warning banner is configured properly 
  template:
    src: issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

# Compliance
# cis: 1.8.1.3
# cis_csc: 5.1
# pci_dss: 7.1
# tsc: CC6.4
- name: Wazuh | 2543 | Ensure remote login warning banner is configured properly
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

# Compliance
# cis: 1.9
# cis_csc: 3.4,3.5
# gdpr_IV: 35.7.d
# gpg_13: 4.2
# hipaa: 164.312.b
# nist_800_53: AU.6,SI.4
# pci_dss: 5.2
# tsc: A1.2
- name: Wazuh | 2548 | Ensure updates, patches, and additional security software are installed
  apt:
    upgrade: yes
    update_cache: yes

# Compliance
# cis: 2.2.1.2
# cis_csc: 6.1
# nist_800_53: CM.1
# pci_dss: 2.2.2
# tsc: CC5.2
- name: Wazuh | 2552 | Ensure systemd-timesyncd is configured | apt
  apt:
    pkg:
    - systemd-timesyncd

- name: Wazuh | 2552 | Ensure systemd-timesyncd is configured | config
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^\s*#*\s*NTP\s*=.*', line: 'NTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org' }
    - { regexp: '^\s*#*\s*FallbackNTP\s*=.*', line: 'FallbackNTP=2.debian.pool.ntp.org 3.debian.pool.ntp.org' }
    - { regexp: '^\s*#*\s*RootDistanceMax\s*=.*', line: 'RootDistanceMax=1' }
  notify: Restart systemd-timesyncd

- name: Wazuh | 2552 | Ensure systemd-timesyncd is configured | service
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started

# Compliance
# cis: 2.2.16
# cis_csc: 9.2
# nist_800_53: CM.1
# pci_dss: 2.2.2
- name: Wazuh | 2569 | Ensure rsync service is not enabled | get all services
  service_facts:

- name: Wazuh | 2569 | Ensure rsync service is not enabled
  service:
    name: rsync
    state: stopped
    enabled : no
  when: ansible_facts.services['rsync'] is defined

# Compliance
# cis: 2.3.4
# cis_csc: 4.5
# gdpr_IV: 35.7.d
# gpg_13: 4.3
# hipaa: 164.312.b
# nist_800_53: CM.1
# pci_dss: 2.2.3
# tsc: CC5.2
- name:  Wazuh | 2574 | Ensure telnet client is not installed
  apt:
    name: telnet
    state: absent
