---

- name: 'Logs collection | Install prerequisites for FileBeat role'
  package:
    name:
      - 'gnupg2'
    state: 'present'
  become: true
  tags:
    - logs_collection

- name: 'Logs collection | Install FileBeat'
  include_role:
    name: 'beats'
  tags:
    - logs_collection

- name: 'Logs collection | Install Rsyslog -> FileBeat integration'
  include_role:
    name: 'filebeat-rsyslog-integration'
  tags:
    - logs_collection
