
- name: Aparavi Platform | Find out if installer exists already
  stat:
    path: "/tmp/linux-installer-latest.run"
  register: app_installer
  tags:
    - platform

- name: Aparavi Platform | Download installer
  get_url:
    url: "{{ aparavi_app_url }}"
    dest: "/tmp/linux-installer-latest.run"
    mode: '0775'
  when: not app_installer.stat.exists
  tags:
    - platform

- name: Aparavi Platform | Retrieving MySQL password
  debug:
    msg:
      - "Check your MySQL user password: {{ mysql_appuser_password }}"
  tags:
    - never
    - platform

- name: Aparavi Platform | Install platform
  ansible.builtin.shell: ./linux-installer-latest.run -- /APPTYPE={{ aparavi_app_type }} /RDBHOST={{redis_cache_address}} /LOCALURL={{ aparavi_platform_addr }} /DBTYPE={{ db_type }} /DBHOST={{ db_addr }} /DBPORT={{ db_port }} /DBUSER={{ db_user }} /DBPSWD={{ db_passwd }} /SILENT /NOSTART
  args:
    chdir: /tmp/
    warn: no
  notify: Restart Aparavi Platform
  tags:
    - platform

- name: Aparavi Platform | Run the Platform
  ansible.builtin.shell: /opt/aparavi-data-ia/{{ aparavi_app_type }}/app/startapp
  tags:
    - platform

- name: Aparavi Platform | Wait until default config file created
  wait_for:
    path: /etc/opt/aparavi-data-ia/{{ aparavi_app_type }}/config/config.json
  tags:
    - platform
