# App.
aparavi_app_type: "aggregator-collector"
aparavi_platform_bind_addr: "preview.aparavi.com"
aparavi_parent_object: "f9975da9-5262-414d-8fd3-e5c565175827"
aparavi_app_url: "https://aparavi.jfrog.io/artifactory/aparavi-installers-public/linux-installer-latest.run"

# Database.
db_type: "mysql"
db_addr: "127.0.0.1"
db_port: "3306"
db_user: "aparavi_app"
db_name: "{{ mysql_db_name }}"
db_passwd: "{{ mysql_appuser_password }}"
