---
- name: Redis | Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
  tags:
    - install
    - redis_server

- name: Redis | Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path }}"
    state: directory
    mode: 0755
  tags:
    - install
    - redis_server

- name: Redis | Ensure Redis is installed.
  apt:
    name: "{{ redis_package }}"
    state: present
  tags:
    - install
    - redis_server

- name: Redis | Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
  tags:
    - install
    - redis_server