# App.
aparavi_app_type: "platform"
aparavi_platform_addr: "test.paas.aparavi.com"
aparavi_parent_object: "f9975da9-5262-414d-8fd3-e5c565175827"
aparavi_app_url: "https://aparavi.jfrog.io/artifactory/aparavi-installers-public/linux-installer-latest.run"

aparavi_platform_client_phone: "123-456-7890"
aparavi_platform_client_email: "{{ node_meta_service_instance }}@aparavi.com"
aparavi_platform_client_username: "{{ node_meta_service_instance }}"
aparavi_platform_client_password_gen: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits') }}"
aparavi_platform_client_objectid: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbb{{ node_meta_service_instance }}"
# Database.
db_type: "mysql"
db_addr: "127.0.0.1"
db_port: "3306"
db_user: "aparavi_app"
db_name: "{{ mysql_db_name }}"
db_passwd: "{{ mysql_appuser_password }}"

# Redis cache.
redis_cache_address: "127.0.0.1"
